import { FaWifi, FaCoffee, FaBath, FaParking, FaSwimmingPool, FaHotdog, FaStopwatch, FaCocktail } from 'react-icons/fa';
import images from '../assets';

export const roomData = [
  {
    id: 1,
    name: '高级客房',
    description:
      '这间高级客房为您提供舒适优雅的住宿体验。宽敞的空间设计，配备现代化设施和贴心服务，让您在旅途中享受家的温馨。我们致力于为您打造难忘的住宿回忆。',
    facilities: [
      { name: '无线网络', icon: FaWifi },
      { name: '咖啡', icon: FaCoffee },
      { name: '浴室', icon: FaBath },
      { name: '停车位', icon: FaParking },
      { name: '游泳池', icon: FaSwimmingPool },
      { name: '早餐', icon: FaHotdog },
      { name: '健身房', icon: FaStopwatch },
      { name: '饮品', icon: FaCocktail },
    ],
    size: 30,
    maxPerson: 1,
    price: 115,
    image: images.Room1Img,
    imageLg: images.Room1ImgLg,
  },
  {
    id: 2,
    name: '特色客房',
    description:
      '这间特色客房融合了现代设计与传统元素，为您提供独特的住宿体验。精心布置的空间，让您感受别样的舒适与温馨。',
    facilities: [
      { name: '无线网络', icon: FaWifi },
      { name: '咖啡', icon: FaCoffee },
      { name: '浴室', icon: FaBath },
      { name: '停车位', icon: FaParking },
      { name: '游泳池', icon: FaSwimmingPool },
      { name: '早餐', icon: FaHotdog },
      { name: '健身房', icon: FaStopwatch },
      { name: '饮品', icon: FaCocktail },
    ],
    size: 70,
    maxPerson: 2,
    price: 220,
    image: images.Room2Img,
    imageLg: images.Room2ImgLg,
  },
  {
    id: 3,
    name: '豪华客房',
    description:
      '这间豪华客房为您提供顶级的住宿体验。宽敞的空间，精致的装饰，让您享受奢华与舒适的完美结合。',
    facilities: [
      { name: '无线网络', icon: FaWifi },
      { name: '咖啡', icon: FaCoffee },
      { name: '浴室', icon: FaBath },
      { name: '停车位', icon: FaParking },
      { name: '游泳池', icon: FaSwimmingPool },
      { name: '早餐', icon: FaHotdog },
      { name: '健身房', icon: FaStopwatch },
      { name: '饮品', icon: FaCocktail },
    ],
    size: 50,
    maxPerson: 3,
    price: 265,
    image: images.Room3Img,
    imageLg: images.Room3ImgLg,
  },
  {
    id: 4,
    name: '奢华客房',
    description:
      '这间奢华客房为您提供最顶级的住宿体验。精心设计的空间，高品质的设施，让您感受无与伦比的奢华与舒适。',
    facilities: [
      { name: '无线网络', icon: FaWifi },
      { name: '咖啡', icon: FaCoffee },
      { name: '浴室', icon: FaBath },
      { name: '停车位', icon: FaParking },
      { name: '游泳池', icon: FaSwimmingPool },
      { name: '早餐', icon: FaHotdog },
      { name: '健身房', icon: FaStopwatch },
      { name: '饮品', icon: FaCocktail },
    ],
    size: 50,
    maxPerson: 4,
    price: 289,
    image: images.Room4Img,
    imageLg: images.Room4ImgLg,
  },
  {
    id: 5,
    name: '奢华套房',
    description:
      '这间奢华套房为您提供最顶级的住宿体验。宽敞的起居空间，独立的卧室区域，让您享受私密与奢华的完美结合。',
    facilities: [
      { name: '无线网络', icon: FaWifi },
      { name: '咖啡', icon: FaCoffee },
      { name: '浴室', icon: FaBath },
      { name: '停车位', icon: FaParking },
      { name: '游泳池', icon: FaSwimmingPool },
      { name: '早餐', icon: FaHotdog },
      { name: '健身房', icon: FaStopwatch },
      { name: '饮品', icon: FaCocktail },
    ],
    size: 90,
    maxPerson: 5,
    price: 320,
    image: images.Room5Img,
    imageLg: images.Room5ImgLg,
  },
  {
    id: 6,
    name: '豪华客房',
    description:
      '这间豪华客房为您提供舒适的住宿体验。精心设计的空间，现代化的设施，让您享受高品质的住宿服务。',
    facilities: [
      { name: '无线网络', icon: FaWifi },
      { name: '咖啡', icon: FaCoffee },
      { name: '浴室', icon: FaBath },
      { name: '停车位', icon: FaParking },
      { name: '游泳池', icon: FaSwimmingPool },
      { name: '早餐', icon: FaHotdog },
      { name: '健身房', icon: FaStopwatch },
      { name: '饮品', icon: FaCocktail },
    ],
    size: 45,
    maxPerson: 6,
    price: 344,
    image: images.Room6Img,
    imageLg: images.Room6ImgLg,
  },
  {
    id: 7,
    name: '奢华客房',
    description:
      '这间奢华客房为您提供最顶级的住宿体验。精心设计的空间，高品质的设施，让您感受无与伦比的奢华与舒适。',
    facilities: [
      { name: '无线网络', icon: FaWifi },
      { name: '咖啡', icon: FaCoffee },
      { name: '浴室', icon: FaBath },
      { name: '停车位', icon: FaParking },
      { name: '游泳池', icon: FaSwimmingPool },
      { name: '早餐', icon: FaHotdog },
      { name: '健身房', icon: FaStopwatch },
      { name: '饮品', icon: FaCocktail },
    ],
    size: 84,
    maxPerson: 7,
    price: 389,
    image: images.Room7Img,
    imageLg: images.Room7ImgLg,
  },
  {
    id: 8,
    name: '豪华客房',
    description:
      '这间豪华客房为您提供舒适的住宿体验。精心设计的空间，现代化的设施，让您享受高品质的住宿服务。',
    facilities: [
      { name: '无线网络', icon: FaWifi },
      { name: '咖啡', icon: FaCoffee },
      { name: '浴室', icon: FaBath },
      { name: '停车位', icon: FaParking },
      { name: '游泳池', icon: FaSwimmingPool },
      { name: '早餐', icon: FaHotdog },
      { name: '健身房', icon: FaStopwatch },
      { name: '饮品', icon: FaCocktail },
    ],
    size: 48,
    maxPerson: 8,
    price: 499,
    image: images.Room8Img,
    imageLg: images.Room8ImgLg,
  },
];
